// Enhanced mock data with subcategories and products
export const categoryData = {
  livestock: {
    name: "Livestock & Pets",
    description: "Quality livestock and pet products from certified farms",
    icon: "🐄",
    subcategories: [
      { id: "cattle", name: "Cattle", description: "Beef and dairy cattle", productCount: 78, image: "/farm-animals/cows.png" },
      { id: "poultry", name: "Poultry", description: "Chickens, ducks, and more", productCount: 234, image: "/farm-animals/chickens.png" },
      { id: "goats", name: "Goats", description: "Meat and dairy goats", productCount: 45, image: "/farm-animals/goats.png" },
      { id: "sheep", name: "Sheep", description: "Quality sheep breeds", productCount: 67, image: "/farm-animals/sheeps.png" },
      { id: "turkey", name: "Turkey", description: "Quality turkey breeds", productCount: 67, image: "/farm-animals/turkey.png" },
      { id: "pet", name: "Pets", description: "Fine Pets for breeds", productCount: 67, image: "/farm-animals/rabbits.png" },
    ],
    products: {
      cattle: [
        {
          id: "9",
          title: "Holstein Dairy Cow",
          price: 450000,
          location: "Plateau, Nigeria",
          seller: "Cattle Ranch Ltd",
          rating: 4.7,
          image: "/farm-animals/bull.jpg",
          boosted: false,
          subcategory: "cattle",
          description: "Healthy Holstein dairy cow with excellent milk production",
          condition: "New",
          postedDate: "2024-01-14",
        },
        {
          id: "10",
          title: "White Fulani Bull",
          price: 600000,
          location: "Kaduna, Nigeria",
          seller: "Northern Cattle Co.",
          rating: 4.9,
          image: "/placeholder.svg?height=200&width=300&text=Fulani+Bull",
          boosted: true,
          subcategory: "cattle",
          description: "Strong White Fulani bull, ideal for breeding or meat",
          condition: "New",
          postedDate: "2024-03-22",
        },
      ],
      poultry: [
        {
          id: "11",
          title: "Day-old Broiler Chicks (100 pcs)",
          price: 18000,
          location: "Ibadan, Nigeria",
          seller: "Poultry Hatchery Ltd",
          rating: 4.4,
          image: "/placeholder.svg?height=200&width=300&text=Broiler+Chicks",
          boosted: true,
          subcategory: "poultry",
          description: "Fast-growing broiler chicks perfect for commercial meat production",
          condition: "New",
          postedDate: "2024-04-05",
        },
        {
          id: "12",
          title: "Local Egg-laying Hens",
          price: 3500,
          location: "Enugu, Nigeria",
          seller: "Farm Fresh Eggs",
          rating: 4.2,
          image: "/placeholder.svg?height=200&width=300&text=Egg+Hens",
          boosted: false,
          subcategory: "poultry",
          description: "Healthy hens already laying eggs, perfect for backyard farming",
          condition: "Used",
          postedDate: "2024-05-11",
        },
      ],
      goats: [
        {
          id: "13",
          title: "Boer Goat (Male)",
          price: 70000,
          location: "Ilorin, Nigeria",
          seller: "Goat World Farms",
          rating: 4.6,
          image: "/placeholder.svg?height=200&width=300&text=Boer+Goat",
          boosted: true,
          subcategory: "goats",
          description: "Purebred Boer goat ideal for meat production",
          condition: "New",
          postedDate: "2024-02-08",
        },
      ],
      sheep: [
        {
          id: "14",
          title: "West African Dwarf Sheep",
          price: 50000,
          location: "Ogbomosho, Nigeria",
          seller: "Sheep Haven",
          rating: 4.5,
          image: "/placeholder.svg?height=200&width=300&text=Dwarf+Sheep",
          boosted: false,
          subcategory: "sheep",
          description: "Small but hardy local breed suitable for mixed farming",
          condition: "New",
          postedDate: "2024-03-29",
        },
      ],
    },
  },
  services: {
    name: "Services",
    description: "Professional agricultural services for every need",
    icon: "🤝",
    subcategories: [
      { id: "tractor-hiring", name: "Tractor Hiring", productCount: 6, image: "" },
      { id: "farm-setup", name: "Farm Setup", productCount: 8, image: "" },
      { id: "veterinary", name: "Veterinary", productCount: 4, image: "" },
    ],
    products: {
      "farm-setup": [
        {
          id: "10",
          title: "Complete Farm Setup Consultation",
          price: 250000,
          location: "Abuja, Nigeria",
          seller: "AgroTech Nigeria",
          rating: 4.8,
          image: "/placeholder.svg?height=200&width=300&text=Farm+Setup",
          boosted: false,
          subcategory: "farm-setup",
          description: "Comprehensive support for starting your own farm",
          condition: "Service",
          postedDate: "2024-01-10",
        },
      ],
      "tractor-hiring": [
        {
          id: "11",
          title: "Modern Tractor for Hire",
          price: 50000,
          location: "Kano, Nigeria",
          seller: "GreenFarm Services",
          rating: 4.5,
          image: "/placeholder.svg?height=200&width=300&text=Tractor+Hiring",
          boosted: true,
          subcategory: "tractor-hiring",
          description: "Hire a modern, fuel-efficient tractor for your farm work",
          condition: "Service",
          postedDate: "2024-02-05",
        },
      ],
      "veterinary": [
        {
          id: "12",
          title: "Livestock Veterinary Visit",
          price: 30000,
          location: "Ibadan, Nigeria",
          seller: "VetCare Agro",
          rating: 4.7,
          image: "/placeholder.svg?height=200&width=300&text=Veterinary+Service",
          boosted: false,
          subcategory: "veterinary",
          description: "On-site veterinary services for your livestock",
          condition: "Service",
          postedDate: "2024-03-15",
        },
      ],
    },
  },
  insurance: {
    name: "Agro Insurance",
    description: "Reliable insurance options for farms, crops, and equipment",
    icon: "🛡️",
    subcategories: [
      { id: "crop-insurance", name: "Crop Insurance", productCount: 3, image: "" },
      { id: "livestock-insurance", name: "Livestock Insurance", productCount: 2, image: "" },
      { id: "equipment-insurance", name: "Farm Equipment Insurance", productCount: 1, image: "" },
      { id: "weather-insurance", name: "Weather Insurance", productCount: 2, image: "" },
    ],
    products: {
      "crop-insurance": [
        {
          id: "20",
          title: "Maize Crop Insurance",
          price: 12000,
          location: "Kaduna, Nigeria",
          seller: "AgroProtect Ltd",
          rating: 4.5,
          image: "/placeholder.svg?height=200&width=300&text=Crop+Insurance",
          boosted: false,
          subcategory: "crop-insurance",
          description: "Protect your maize farm from unforeseen crop losses.",
          condition: "Insurance",
          postedDate: "2024-02-15",
        },
        {
          id: "21",
          title: "Rice Farm Insurance Plan",
          price: 15000,
          location: "Lafia, Nigeria",
          seller: "GreenShield Agro",
          rating: 4.2,
          image: "/placeholder.svg?height=200&width=300&text=Rice+Insurance",
          boosted: false,
          subcategory: "crop-insurance",
          description: "Comprehensive insurance plan for rice farmers.",
          condition: "Insurance",
          postedDate: "2024-03-05",
        },
        {
          id: "22",
          title: "General Crop Coverage",
          price: 10000,
          location: "Benue, Nigeria",
          seller: "FarmSure",
          rating: 4.0,
          image: "/placeholder.svg?height=200&width=300&text=Crop+Coverage",
          boosted: false,
          subcategory: "crop-insurance",
          description: "Affordable crop insurance for small farms.",
          condition: "Insurance",
          postedDate: "2024-04-12",
        },
      ],
      "livestock-insurance": [
        {
          id: "23",
          title: "Cattle Loss Protection",
          price: 18000,
          location: "Jos, Nigeria",
          seller: "SafeLivestock",
          rating: 4.6,
          image: "/placeholder.svg?height=200&width=300&text=Cattle+Insurance",
          boosted: false,
          subcategory: "livestock-insurance",
          description: "Coverage for livestock loss due to disease or theft.",
          condition: "Insurance",
          postedDate: "2024-02-28",
        },
        {
          id: "24",
          title: "Goat & Sheep Coverage",
          price: 10000,
          location: "Ibadan, Nigeria",
          seller: "AnimalSecure",
          rating: 4.3,
          image: "/placeholder.svg?height=200&width=300&text=Goat+Insurance",
          boosted: false,
          subcategory: "livestock-insurance",
          description: "Insurance for small ruminants on your farm.",
          condition: "Insurance",
          postedDate: "2024-03-10",
        },
      ],
      "equipment-insurance": [
        {
          id: "25",
          title: "Tractor Insurance Plan",
          price: 25000,
          location: "Ilorin, Nigeria",
          seller: "EquipSure",
          rating: 4.4,
          image: "/placeholder.svg?height=200&width=300&text=Tractor+Insurance",
          boosted: false,
          subcategory: "equipment-insurance",
          description: "Protect your farming equipment from damages or theft.",
          condition: "Insurance",
          postedDate: "2024-01-20",
        },
      ],
      "weather-insurance": [
        {
          id: "26",
          title: "Drought Protection Cover",
          price: 20000,
          location: "Kano, Nigeria",
          seller: "AgroWeatherSecure",
          rating: 4.1,
          image: "/placeholder.svg?height=200&width=300&text=Drought+Insurance",
          boosted: false,
          subcategory: "weather-insurance",
          description: "Be prepared for unexpected weather changes.",
          condition: "Insurance",
          postedDate: "2024-02-18",
        },
        {
          id: "27",
          title: "Flood Risk Plan",
          price: 22000,
          location: "Bayelsa, Nigeria",
          seller: "ClimateGuard",
          rating: 4.3,
          image: "/placeholder.svg?height=200&width=300&text=Flood+Insurance",
          boosted: false,
          subcategory: "weather-insurance",
          description: "Get covered against flood damages to your crops.",
          condition: "Insurance",
          postedDate: "2024-03-01",
        },
      ],
    },
  },
  equipments: {
    name: "Tractor / Farm Machines",
    description: "Machines and tools to support modern farming",
    icon: "🔧",
    subcategories: [
      { id: "tractor", name: "Tractor" },
      { id: "sheller", name: "Sheller" },
      { id: "sprayer", name: "Sprayer" },
      { id: "knapsack", name: "Knapsack Sprayer" },
      { id: "fish-pond", name: "Fish Pond" },
      { id: "others", name: "Others" },
    ],
    products: {
      tractor: [
        {
          id: "tractor-1",
          title: "John Deere 5055E",
          price: 12000,
          location: "Kaduna, Nigeria",
          seller: "Green Fields Ltd.",
          rating: 4.5,
          image: "/images/tractor1.jpg",
          boosted: true,
          subcategory: "tractor",
          description: "55HP 4WD tractor ideal for ploughing and towing",
          condition: "inStock",
          postedDate: "2024-06-10",
        },
        {
          id: "tractor-2",
          title: "Massey Ferguson 240",
          price: 9500,
          location: "Benue, Nigeria",
          seller: "AgroWorld Equipments",
          rating: 4.3,
          image: "/images/tractor2.jpg",
          boosted: false,
          subcategory: "tractor",
          description: "Reliable 2WD tractor suitable for various farm tasks",
          condition: "Used",
          postedDate: "2024-06-08",
        },
      ],
      sheller: [
        {
          id: "sheller-1",
          title: "Maize Sheller Electric",
          price: 750,
          location: "Kano, Nigeria",
          seller: "FarmTech Co.",
          rating: 4.1,
          image: "/images/sheller1.jpg",
          boosted: false,
          subcategory: "sheller",
          description: "Electric-powered maize sheller for large-scale use",
          condition: "inStock",
          postedDate: "2024-06-11",
        },
        {
          id: "sheller-2",
          title: "Manual Maize Sheller",
          price: 200,
          location: "Jos, Nigeria",
          seller: "Rural Agro Tools",
          rating: 3.9,
          image: "/images/sheller2.jpg",
          boosted: false,
          subcategory: "sheller",
          description: "Hand-operated maize sheller for small farms",
          condition: "Used",
          postedDate: "2024-05-30",
        },
      ],
      sprayer: [
        {
          id: "sprayer-1",
          title: "Boom Sprayer",
          price: 1150,
          location: "Ibadan, Nigeria",
          seller: "Field Masters",
          rating: 4.4,
          image: "/images/sprayer1.jpg",
          boosted: true,
          subcategory: "sprayer",
          description: "Field boom sprayer with wide spray range",
          condition: "inStock",
          postedDate: "2024-06-01",
        },
        {
          id: "sprayer-2",
          title: "Motorized Mist Blower",
          price: 890,
          location: "Ilorin, Nigeria",
          seller: "AgriSpray Ltd.",
          rating: 4.0,
          image: "/images/sprayer2.jpg",
          boosted: false,
          subcategory: "sprayer",
          description: "Effective mist blower for orchard and tall crops",
          condition: "Used",
          postedDate: "2024-05-22",
        },
      ],
      knapsack: [
        {
          id: "knapsack-1",
          title: "16L Manual Knapsack",
          price: 65,
          location: "Abeokuta, Nigeria",
          seller: "Farm Ease",
          rating: 3.8,
          image: "/images/knapsack1.jpg",
          boosted: false,
          subcategory: "knapsack",
          description: "16-liter manual knapsack sprayer for daily farm use",
          condition: "inStock",
          postedDate: "2024-06-02",
        },
        {
          id: "knapsack-2",
          title: "Battery-Powered Knapsack",
          price: 110,
          location: "Port Harcourt, Nigeria",
          seller: "EasySpray NG",
          rating: 4.2,
          image: "/images/knapsack2.jpg",
          boosted: true,
          subcategory: "knapsack",
          description: "Rechargeable knapsack sprayer for easy spraying",
          condition: "inStock",
          postedDate: "2024-06-05",
        },
      ],
      "fish-pond": [
        {
          id: "fish-pond-1",
          title: "Tarp Fish Pond - 1000L",
          price: 200,
          location: "Calabar, Nigeria",
          seller: "BlueFish Farms",
          rating: 4.0,
          image: "/images/fishpond1.jpg",
          boosted: false,
          subcategory: "fish-pond",
          description: "Durable tarpaulin fish pond for small-scale farming",
          condition: "inStock",
          postedDate: "2024-05-28",
        },
        {
          id: "fish-pond-2",
          title: "PVC Fish Tank - 2000L",
          price: 450,
          location: "Warri, Nigeria",
          seller: "AquaGrow Ltd.",
          rating: 4.4,
          image: "/images/fishpond2.jpg",
          boosted: true,
          subcategory: "fish-pond",
          description: "High-capacity PVC fish tank suitable for large farms",
          condition: "inStock",
          postedDate: "2024-06-06",
        },
      ],
      others: [
        {
          id: "others-1",
          title: "Farm Weeder",
          price: 35,
          location: "Zaria, Nigeria",
          seller: "AgroTools Hub",
          rating: 3.7,
          image: "/images/others1.jpg",
          boosted: false,
          subcategory: "others",
          description: "Manual weeder tool for row crops",
          condition: "Used",
          postedDate: "2024-05-18",
        },
        {
          id: "others-2",
          title: "Chisel Plough",
          price: 550,
          location: "Makurdi, Nigeria",
          seller: "SoilTech Ventures",
          rating: 4.1,
          image: "/images/others2.jpg",
          boosted: true,
          subcategory: "others",
          description: "Heavy-duty plough for breaking hard soil",
          condition: "inStock",
          postedDate: "2024-06-03",
        },
      ],
    },
  },
  animalMating: {
    name: "Animal Mating",
    description: "Mating services and breeding options",
    icon: "💞",
    subcategories: [
      { id: "dog", name: "Dog" },
      { id: "goat", name: "Goat" },
      { id: "pig", name: "Pig" },
      { id: "ai-service", name: "AI Service" },
      { id: "natural", name: "Natural Mating" },
    ],
    products: {
      dog: [
        {
          id: "dog-1",
          title: "German Shepherd Stud",
          price: 30000,
          location: "Abuja",
          seller: "K9 Breeders Hub",
          rating: 4.6,
          image: "/german_shepherd_stud.jpg",
          boosted: true,
          subcategory: "dog",
          description: "Purebred German Shepherd available for stud services.",
          condition: "Used",
          postedDate: "2024-06-15",
        },
        {
          id: "dog-2",
          title: "Labrador Retriever Mating",
          price: 25000,
          location: "Lagos",
          seller: "Elite Paws Nigeria",
          rating: 4.3,
          image: "/labrador_stud.jpg",
          boosted: false,
          subcategory: "dog",
          description: "Healthy male Labrador ready for mating services.",
          condition: "Used",
          postedDate: "2024-06-10",
        },
      ],
      goat: [
        {
          id: "goat-1",
          title: "Boer Goat Breeding",
          price: 15000,
          location: "Ibadan",
          seller: "Goat Genetics Ltd.",
          rating: 4.2,
          image: "/boer_goat.jpg",
          boosted: false,
          subcategory: "goat",
          description: "Boer buck available for quality goat breeding.",
          condition: "inStock",
          postedDate: "2024-06-07",
        },
        {
          id: "goat-2",
          title: "West African Dwarf Mating",
          price: 12000,
          location: "Ilorin",
          seller: "DwarfGoat Farms",
          rating: 4.0,
          image: "/dwarf_goat.jpg",
          boosted: false,
          subcategory: "goat",
          description: "Dwarf male goat ready for controlled mating.",
          condition: "Used",
          postedDate: "2024-06-03",
        },
      ],
      pig: [
        {
          id: "pig-1",
          title: "Large White Boar Service",
          price: 20000,
          location: "Benin",
          seller: "Swine Pro Nigeria",
          rating: 4.1,
          image: "/white_boar.jpg",
          boosted: true,
          subcategory: "pig",
          description: "Large White boar available for mating services.",
          condition: "Used",
          postedDate: "2024-06-09",
        },
        {
          id: "pig-2",
          title: "Landrace Pig Stud",
          price: 22000,
          location: "Abeokuta",
          seller: "Premium Pigs Ltd.",
          rating: 4.4,
          image: "/landrace_pig.jpg",
          boosted: false,
          subcategory: "pig",
          description: "Healthy Landrace boar ready for artificial or natural mating.",
          condition: "inStock",
          postedDate: "2024-06-12",
        },
      ],
      "ai-service": [
        {
          id: "ai-service-1",
          title: "AI Service for Cattle",
          price: 40000,
          location: "Jos",
          seller: "Cattle Genetics NG",
          rating: 4.7,
          image: "/ai_cattle.jpg",
          boosted: true,
          subcategory: "ai-service",
          description: "Artificial Insemination for improved cattle genetics.",
          condition: "inStock",
          postedDate: "2024-06-01",
        },
        {
          id: "ai-service-2",
          title: "AI for Goats and Sheep",
          price: 18000,
          location: "Enugu",
          seller: "Smart Breed Services",
          rating: 4.5,
          image: "/ai_goat_sheep.jpg",
          boosted: false,
          subcategory: "ai-service",
          description: "Artificial insemination for small ruminants.",
          condition: "inStock",
          postedDate: "2024-06-06",
        },
      ],
      natural: [
        {
          id: "natural-1",
          title: "Natural Mating for Rams",
          price: 10000,
          location: "Kano",
          seller: "SheepPro Mating",
          rating: 4.0,
          image: "ram_mating.jpg",
          boosted: false,
          subcategory: "natural",
          description: "Healthy ram for natural sheep mating services.",
          condition: "Used",
          postedDate: "2024-06-04",
        },
        {
          id: "natural-2",
          title: "Bull Mating Service",
          price: 35000,
          location: "Makurdi",
          seller: "StrongBull Genetics",
          rating: 4.6,
          image: "bull_mating.jpg",
          boosted: true,
          subcategory: "natural",
          description: "High-performing bull for natural cattle mating.",
          condition: "Used",
          postedDate: "2024-06-08",
        },
      ],
    },
  },
  agroChemicals: {
    name: "Agro Chemicals / Pesticides",
    description: "Protect and nourish crops with reliable chemicals",
    icon: "🧴",
    subcategories: [
      { id: "herbicide", name: "Herbicide" },
      { id: "pesticide", name: "Pesticide" },
      { id: "fungicide", name: "Fungicide" },
    ],
    products: {
      herbicide: [
        {
          id: "herbicide-001",
          title: "Paraquat 276 SL",
          price: 3500,
          location: "Ibadan, Nigeria",
          seller: "AgroChem Distributors",
          rating: 4.1,
          image: "/images/products/herbicide-paraquat.jpg",
          boosted: false,
          subcategory: "herbicide",
          description: "Fast-acting contact herbicide for effective weed control.",
          condition: "inStock",
          postedDate: "2024-05-09",
        },
        {
          id: "herbicide-002",
          title: "Glyphosate 360 SL",
          price: 4000,
          location: "Kaduna, Nigeria",
          seller: "CropCare Ventures",
          rating: 4.3,
          image: "/images/products/herbicide-glyphosate.jpg",
          boosted: true,
          subcategory: "herbicide",
          description: "Systemic herbicide ideal for clearing land and field prep.",
          condition: "inStock",
          postedDate: "2024-05-11",
        },
      ],
      pesticide: [
        {
          id: "pesticide-001",
          title: "Lambda Super",
          price: 2800,
          location: "Abeokuta, Nigeria",
          seller: "Green Guard Agro",
          rating: 4.0,
          image: "/images/products/pesticide-lambda.jpg",
          boosted: false,
          subcategory: "pesticide",
          description: "Broad-spectrum pesticide for crop pest control.",
          condition: "inStock",
          postedDate: "2024-05-10",
        },
        {
          id: "pesticide-002",
          title: "Cypermethrin EC",
          price: 3200,
          location: "Benin City, Nigeria",
          seller: "DefendAgro Ltd.",
          rating: 4.2,
          image: "/images/products/pesticide-cypermethrin.jpg",
          boosted: false,
          subcategory: "pesticide",
          description: "Effective against a wide range of insects on crops.",
          condition: "inStock",
          postedDate: "2024-05-12",
        },
      ],
      fungicide: [
        {
          id: "fungicide-001",
          title: "Ridomil Gold",
          price: 4500,
          location: "Jos, Nigeria",
          seller: "Plant Shield Co.",
          rating: 4.5,
          image: "/images/products/fungicide-ridomil.jpg",
          boosted: true,
          subcategory: "fungicide",
          description: "Protects crops from fungal diseases and blights.",
          condition: "inStock",
          postedDate: "2024-05-08",
        },
        {
          id: "fungicide-002",
          title: "Mancozeb 75% WP",
          price: 3000,
          location: "Enugu, Nigeria",
          seller: "AgriSure Chemicals",
          rating: 4.1,
          image: "/images/products/fungicide-mancozeb.jpg",
          boosted: false,
          subcategory: "fungicide",
          description: "Preventive fungicide for foliar diseases.",
          condition: "inStock",
          postedDate: "2024-05-06",
        },
      ],
    },
  },
  fruits: {
    name: "Fruits & Vegetables",
    description: "Fresh fruits and vegetables harvested daily from local farms",
    icon: "🍎",
    subcategories: [
      {
        id: "fresh-fruits",
        name: "Fresh Fruits",
        description: "Seasonal fresh fruits",
        productCount: 89,
        image: "/Fruits",
      },
      {
        id: "vegetables",
        name: "Vegetables",
        description: "Farm-fresh vegetables",
        productCount: 156,
        image: "/Vegetables",
      },
      {
        id: "herbs",
        name: "Herbs",
        description: "Aromatic cooking herbs",
        productCount: 34,
        image: "/Herbs",
      },
      {
        id: "spices",
        name: "Spices",
        description: "Traditional spices",
        productCount: 67,
        image: "/Spices",
      },
    ],
    products: {
      vegetables: [
        {
          id: "8",
          title: "Fresh Tomatoes - 50kg",
          price: 15000,
          location: "Kano, Nigeria",
          seller: "Musa Agriculture",
          rating: 4.6,
          image: "/placeholder.svg?height=200&width=300&text=Fresh+Tomatoes",
          boosted: true,
          subcategory: "vegetables",
          description: "Farm-fresh tomatoes harvested daily",
          condition: "New",
          postedDate: "2024-01-15",
        },
        {
          id: "9",
          title: "Green Spinach - 25 Bunches",
          price: 7000,
          location: "Ibadan, Nigeria",
          seller: "FreshLeaf Farms",
          rating: 4.8,
          image: "/placeholder.svg?height=200&width=300&text=Green+Spinach",
          boosted: false,
          subcategory: "vegetables",
          description: "Organic spinach with no pesticides, sold in bundles",
          condition: "New",
          postedDate: "2025-07-15",
        },
        {
          id: "10",
          title: "Cabbage Heads - 10kg",
          price: 6000,
          location: "Jos, Nigeria",
          seller: "Plateau Growers",
          rating: 4.5,
          image: "/placeholder.svg?height=200&width=300&text=Cabbage+Heads",
          boosted: false,
          subcategory: "vegetables",
          description: "Crunchy green cabbage freshly harvested",
          condition: "New",
          postedDate: "2025-07-25",
        },
        {
          id: "11",
          title: "Okra Crates - 40kg",
          price: 12000,
          location: "Makurdi, Nigeria",
          seller: "Benue Roots",
          rating: 4.7,
          image: "/placeholder.svg?height=200&width=300&text=Okra+Crates",
          boosted: true,
          subcategory: "vegetables",
          description: "Tender okra pods, perfect for soups and stews",
          condition: "New",
          postedDate: "2025-08-05",
        },
      ],
      "fresh-fruits": [
        {
          id: "12",
          title: "Pineapples - 12 Pieces",
          price: 8000,
          location: "Enugu, Nigeria",
          seller: "Tropical Farm Enugu",
          rating: 4.9,
          image: "/placeholder.svg?height=200&width=300&text=Pineapples",
          boosted: true,
          subcategory: "fresh-fruits",
          description: "Sweet, juicy pineapples perfect for juicing or eating fresh",
          condition: "New",
          postedDate: "2025-08-03",
        },
        {
          id: "13",
          title: "Banana Bunches - 25kg",
          price: 9500,
          location: "Abeokuta, Nigeria",
          seller: "YellowTree Farms",
          rating: 4.6,
          image: "/placeholder.svg?height=200&width=300&text=Banana+Bunches",
          boosted: false,
          subcategory: "fresh-fruits",
          description: "Naturally ripened banana bunches ready for markets or homes",
          condition: "New",
          postedDate: "2025-08-01",
        },
        {
          id: "14",
          title: "Mango Crates - 30kg",
          price: 13500,
          location: "Minna, Nigeria",
          seller: "Savannah Fruits Co.",
          rating: 4.8,
          image: "/placeholder.svg?height=200&width=300&text=Mango+Crates",
          boosted: false,
          subcategory: "fresh-fruits",
          description: "Sweet mangoes, hand-picked and packed in crates",
          condition: "New",
          postedDate: "2025-08-06",
        },
      ],
      herbs: [
        {
          id: "15",
          title: "Basil Leaves - 500g",
          price: 2500,
          location: "Abuja, Nigeria",
          seller: "Green Aroma Farms",
          rating: 4.5,
          image: "/placeholder.svg?height=200&width=300&text=Basil+Leaves",
          boosted: false,
          subcategory: "herbs",
          description: "Aromatic basil leaves perfect for cooking and garnishing",
          condition: "New",
          postedDate: "2025-08-05",
        },
        {
          id: "16",
          title: "Fresh Mint - 200g",
          price: 1800,
          location: "Ilorin, Nigeria",
          seller: "MintFresh Farms",
          rating: 4.7,
          image: "/placeholder.svg?height=200&width=300&text=Fresh+Mint",
          boosted: true,
          subcategory: "herbs",
          description: "Cool and aromatic mint leaves for tea, drinks, or meals",
          condition: "New",
          postedDate: "2025-08-06",
        },
        {
          id: "17",
          title: "Scent Leaf (Efirin) - 1kg",
          price: 3000,
          location: "Osogbo, Nigeria",
          seller: "NaijaHerbs",
          rating: 4.9,
          image: "/placeholder.svg?height=200&width=300&text=Scent+Leaf",
          boosted: false,
          subcategory: "herbs",
          description: "Locally grown scent leaf used in traditional cooking",
          condition: "New",
          postedDate: "2025-08-04",
        },
      ],
    },
  },
  seedlings: {
    name: "Seedlings",
    description: "High-quality seedlings for increased productivity",
    icon: "🌱",
    subcategories: [
      { id: "maize", name: "Maize" },
      { id: "soybean", name: "Soybean" },
      { id: "groundnut", name: "Groundnut" },
      { id: "hybrid", name: "Hybrid" },
      { id: "open", name: "Open-pollination" },
    ],
    products: {
      maize: [
        {
          id: "mz-001",
          title: "Yellow Hybrid Maize Seed",
          price: 2500,
          location: "Kano, Nigeria",
          seller: "SeedCo Farms",
          rating: 4.3,
          image: "/images/maize-yellow.jpg",
          boosted: true,
          subcategory: "maize",
          description: "High-yield yellow hybrid maize seed for commercial farming",
          condition: "inStock",
          postedDate: "2024-05-08",
        },
        {
          id: "mz-002",
          title: "White Maize Seedling",
          price: 2200,
          location: "Zaria, Nigeria",
          seller: "GreenMaize Ltd.",
          rating: 4.1,
          image: "/images/maize-white.jpg",
          boosted: false,
          subcategory: "maize",
          description: "Disease-resistant white maize seedling suitable for all regions",
          condition: "inStock",
          postedDate: "2024-05-09",
        },
      ],
      soybean: [
        {
          id: "sb-001",
          title: "Early Maturity Soybean Seed",
          price: 1800,
          location: "Minna, Nigeria",
          seller: "AgroSoya Seeds",
          rating: 4.0,
          image: "/images/soybean-early.jpg",
          boosted: false,
          subcategory: "soybean",
          description: "Fast-growing soybean variety for early harvest",
          condition: "inStock",
          postedDate: "2024-05-10",
        },
        {
          id: "sb-002",
          title: "High-Oil Soybean Seedling",
          price: 2000,
          location: "Makurdi, Nigeria",
          seller: "RichOil Agro",
          rating: 4.4,
          image: "/images/soybean-oil.jpg",
          boosted: true,
          subcategory: "soybean",
          description: "Soybean seedlings bred for high oil content",
          condition: "inStock",
          postedDate: "2024-05-12",
        },
      ],
      groundnut: [
        {
          id: "gn-001",
          title: "Groundnut Seed - SAMNUT 24",
          price: 2300,
          location: "Ilorin, Nigeria",
          seller: "NutraSeed Farms",
          rating: 4.2,
          image: "/images/groundnut-samnut24.jpg",
          boosted: true,
          subcategory: "groundnut",
          description: "Improved variety, drought-resistant, high productivity",
          condition: "inStock",
          postedDate: "2024-05-07",
        },
        {
          id: "gn-002",
          title: "Organic Groundnut Seedling",
          price: 2100,
          location: "Lokoja, Nigeria",
          seller: "EcoRoots Agro",
          rating: 4.0,
          image: "/images/groundnut-organic.jpg",
          boosted: false,
          subcategory: "groundnut",
          description: "Organically grown seedlings for sustainable farming",
          condition: "inStock",
          postedDate: "2024-05-11",
        },
      ],
      hybrid: [
        {
          id: "hb-001",
          title: "Hybrid Tomato Seedling - Roma VF",
          price: 3000,
          location: "Owerri, Nigeria",
          seller: "TomatoTech Ltd.",
          rating: 4.5,
          image: "/images/tomato-hybrid.jpg",
          boosted: true,
          subcategory: "hybrid",
          description: "Disease-resistant hybrid tomato with extended shelf life",
          condition: "inStock",
          postedDate: "2024-05-06",
        },
        {
          id: "hb-002",
          title: "Hybrid Pepper Seedling - Tatashe",
          price: 2800,
          location: "Aba, Nigeria",
          seller: "PepperYield Agro",
          rating: 4.3,
          image: "/images/pepper-hybrid.jpg",
          boosted: false,
          subcategory: "hybrid",
          description: "High-yield hybrid pepper suitable for all seasons",
          condition: "inStock",
          postedDate: "2024-05-10",
        },
      ],
      open: [
        {
          id: "op-001",
          title: "Open-Pollinated Okra Seed",
          price: 1500,
          location: "Nsukka, Nigeria",
          seller: "Village Agro Seeds",
          rating: 4.1,
          image: "/images/okra-open.jpg",
          boosted: false,
          subcategory: "open",
          description: "Non-GMO okra seed with excellent taste and yield",
          condition: "inStock",
          postedDate: "2024-05-11",
        },
        {
          id: "op-002",
          title: "Open-Pollinated Cucumber Seed",
          price: 1600,
          location: "Akure, Nigeria",
          seller: "FreshStart Seeds",
          rating: 4.0,
          image: "/images/cucumber-open.jpg",
          boosted: true,
          subcategory: "open",
          description: "Vigorous growth and heat tolerance, perfect for open fields",
          condition: "inStock",
          postedDate: "2024-05-08",
        },
      ],
    },
  },
  ornamentals: {
    name: "Horticulture / Ornamental Crops",
    description: "Decorative and aesthetic crops for landscaping",
    icon: "🌸",
    subcategories: [
      { id: "flowers", name: "Flowers" },
      { id: "shrubs", name: "Shrubs" },
      { id: "indoor-plants", name: "Indoor Plants" },
      { id: "landscaping", name: "Landscaping Plants" },
    ],
    products: {
      flowers: [
        {
          id: "rose001",
          title: "Hybrid Rose",
          price: 1500,
          location: "Ibadan, Nigeria",
          seller: "Flora Haven",
          rating: 4.3,
          image: "/images/plants/hybrid-rose.jpg",
          boosted: true,
          subcategory: "flowers",
          description: "Colorful hybrid rose for gardens and events",
          condition: "New",
          postedDate: "2024-05-12",
        },
        {
          id: "hibiscus002",
          title: "Red Hibiscus",
          price: 1000,
          location: "Abeokuta, Nigeria",
          seller: "Tropical Greens",
          rating: 4.1,
          image: "/images/plants/red-hibiscus.jpg",
          boosted: false,
          subcategory: "flowers",
          description: "Tropical flowering plant ideal for fences and aesthetics",
          condition: "New",
          postedDate: "2024-05-10",
        },
      ],
      shrubs: [
        {
          id: "bougainvillea001",
          title: "Bougainvillea",
          price: 2000,
          location: "Benin City, Nigeria",
          seller: "Garden Edge",
          rating: 4.4,
          image: "/images/plants/bougainvillea.jpg",
          boosted: true,
          subcategory: "shrubs",
          description: "Fast-growing shrub perfect for hedges",
          condition: "New",
          postedDate: "2024-05-08",
        },
        {
          id: "croton002",
          title: "Croton Plant",
          price: 1200,
          location: "Calabar, Nigeria",
          seller: "BrightLeaf Nursery",
          rating: 4.2,
          image: "/images/plants/croton.jpg",
          boosted: false,
          subcategory: "shrubs",
          description: "Colorful shrub for indoor or outdoor use",
          condition: "New",
          postedDate: "2024-05-09",
        },
      ],
      "indoor-plants": [
        {
          id: "snakeplant001",
          title: "Snake Plant",
          price: 1800,
          location: "Lagos, Nigeria",
          seller: "Urban Botany",
          rating: 4.5,
          image: "/images/plants/snake-plant.jpg",
          boosted: true,
          subcategory: "indoor-plants",
          description: "Air-purifying plant for indoor decoration",
          condition: "New",
          postedDate: "2024-05-11",
        },
        {
          id: "peace-lily002",
          title: "Peace Lily",
          price: 1500,
          location: "Port Harcourt, Nigeria",
          seller: "Lush Living",
          rating: 4.3,
          image: "/images/plants/peace-lily.jpg",
          boosted: false,
          subcategory: "indoor-plants",
          description: "Low-maintenance plant with white blooms",
          condition: "New",
          postedDate: "2024-05-07",
        },
      ],
      landscaping: [
        {
          id: "grass001",
          title: "Carpet Grass",
          price: 500,
          location: "Owerri, Nigeria",
          seller: "Lawn Masters",
          rating: 4.0,
          image: "/images/plants/carpet-grass.jpg",
          boosted: false,
          subcategory: "landscaping",
          description: "Ground cover for lawns and large spaces",
          condition: "New",
          postedDate: "2024-05-05",
        },
        {
          id: "palmtree002",
          title: "Dwarf Palm Tree",
          price: 10000,
          location: "Uyo, Nigeria",
          seller: "Palm World",
          rating: 4.6,
          image: "/images/plants/dwarf-palm.jpg",
          boosted: true,
          subcategory: "landscaping",
          description: "Ornamental tree suitable for large gardens",
          condition: "New",
          postedDate: "2024-05-03",
        },
      ],
    },
  },
  animalLoan: {
    name: "Animal Loan",
    description: "Loans and support for animal health and care",
    icon: "💵",
    subcategories: [
      { id: "veterinary-loan", name: "Veterinary Loan" },
      { id: "feed-subsidy", name: "Feed Subsidy" },
      { id: "equipment-financing", name: "Equipment Financing" },
      { id: "livestock-purchase", name: "Livestock Purchase Support" },
      { id: "insurance", name: "Livestock Insurance" },
    ],
    products: {
      "veterinary-loan": [
        {
          id: "vetloan-001",
          title: "VetCare Loan Plan",
          price: 20000,
          location: "Ibadan, Nigeria",
          seller: "AgroVet Credit",
          rating: 4.5,
          image: "/images/loans/vetcare-loan.jpg",
          boosted: true,
          subcategory: "veterinary-loan",
          description: "Low-interest loan for emergency veterinary services and animal treatment.",
          condition: "Loan",
          postedDate: "2024-05-10",
        },
      ],
      "feed-subsidy": [
        {
          id: "feedsub-001",
          title: "Feed Support Grant",
          price: "Grant / Subsidy",
          location: "Makurdi, Nigeria",
          seller: "National Feed Board",
          rating: 4.3,
          image: "/images/loans/feed-support.jpg",
          boosted: false,
          subcategory: "feed-subsidy",
          description: "Monthly subsidy program for purchasing quality animal feed.",
          condition: "Grant",
          postedDate: "2024-05-08",
        },
      ],
      "equipment-financing": [
        {
          id: "equiploan-001",
          title: "Livestock Equipment Loan",
          price: "Loan",
          location: "Zaria, Nigeria",
          seller: "AgriTools Finance",
          rating: 4.4,
          image: "/images/loans/equipment-loan.jpg",
          boosted: true,
          subcategory: "equipment-financing",
          description: "Access financing for feeding troughs, water systems, and other livestock equipment.",
          condition: "Loan",
          postedDate: "2024-05-09",
        },
      ],
      "livestock-purchase": [
        {
          id: "animalbuy-001",
          title: "Starter Herd Package",
          price: "Loan / Installment",
          location: "Jos, Nigeria",
          seller: "AgroStart Microfinance",
          rating: 4.6,
          image: "/images/loans/starter-herd.jpg",
          boosted: false,
          subcategory: "livestock-purchase",
          description: "Loan program to support initial livestock purchase (goats, poultry, cattle).",
          condition: "Installment",
          postedDate: "2024-05-07",
        },
      ],
      insurance: [
        {
          id: "animalinsure-001",
          title: "Animal Health Insurance",
          price: "Varies",
          location: "Enugu, Nigeria",
          seller: "FarmSure Insurance Ltd.",
          rating: 4.2,
          image: "/images/loans/livestock-insurance.jpg",
          boosted: true,
          subcategory: "insurance",
          description: "Insurance coverage for livestock health, injury, or loss.",
          condition: "Insured",
          postedDate: "2024-05-06",
        },
      ],
    }
  },
  fertilizers: {
    name: "Fertilizers",
    description: "Soil and crop-specific fertilizers for better yield",
    icon: "🍂",
    subcategories: [
      { id: "npk", name: "NPK" },
      { id: "urea", name: "Urea" },
      { id: "dap", name: "DAP" },
      { id: "soil", name: "Soil" },
      { id: "foliar", name: "Foliar" },
    ],
    products: {
      npk: [
        {
          id: "npk-15-15-15",
          title: "NPK 15-15-15",
          price: 8500,
          location: "Kaduna, Nigeria",
          seller: "AgroChem Distributors",
          rating: 4.3,
          image: "/images/products/npk-15-15-15.jpg",
          boosted: false,
          subcategory: "npk",
          description: "Balanced fertilizer for general-purpose crop nutrition",
          condition: "New",
          postedDate: "2024-05-11",
        },
        {
          id: "npk-20-10-10",
          title: "NPK 20-10-10",
          price: 8700,
          location: "Minna, Nigeria",
          seller: "GreenGrow Supplies",
          rating: 4.5,
          image: "/images/products/npk-20-10-10.jpg",
          boosted: true,
          subcategory: "npk",
          description: "High nitrogen fertilizer to boost plant growth",
          condition: "New",
          postedDate: "2024-05-12",
        },
      ],
      urea: [
        {
          id: "urea-standard",
          title: "Standard Urea",
          price: 7000,
          location: "Sokoto, Nigeria",
          seller: "Fertilizer Depot",
          rating: 4.2,
          image: "/images/products/urea-standard.jpg",
          boosted: false,
          subcategory: "urea",
          description: "High nitrogen content fertilizer for leafy growth",
          condition: "New",
          postedDate: "2024-05-10",
        },
        {
          id: "urea-granular",
          title: "Granular Urea",
          price: 7200,
          location: "Lokoja, Nigeria",
          seller: "AgriBoost Stores",
          rating: 4.4,
          image: "/images/products/urea-granular.jpg",
          boosted: true,
          subcategory: "urea",
          description: "Granulated form for even application and better absorption",
          condition: "New",
          postedDate: "2024-05-13",
        },
      ],
      dap: [
        {
          id: "dap-18-46-0",
          title: "DAP 18-46-0",
          price: 9500,
          location: "Makurdi, Nigeria",
          seller: "PrimeAgro Fertilizers",
          rating: 4.1,
          image: "/images/products/dap-18-46-0.jpg",
          boosted: false,
          subcategory: "dap",
          description: "Ideal for root development and early plant growth",
          condition: "New",
          postedDate: "2024-05-09",
        },
        {
          id: "dap-enhanced",
          title: "Enhanced DAP",
          price: 9800,
          location: "Ilorin, Nigeria",
          seller: "SmartFarm Inputs",
          rating: 4.6,
          image: "/images/products/dap-enhanced.jpg",
          boosted: true,
          subcategory: "dap",
          description: "DAP with added micronutrients for complete nutrition",
          condition: "New",
          postedDate: "2024-05-12",
        },
      ],
      soil: [
        {
          id: "soil-conditioner",
          title: "Soil Conditioner",
          price: 6000,
          location: "Abeokuta, Nigeria",
          seller: "GrowMore Ltd.",
          rating: 4.0,
          image: "/images/products/soil-conditioner.jpg",
          boosted: false,
          subcategory: "soil",
          description: "Improves soil structure and fertility",
          condition: "New",
          postedDate: "2024-05-08",
        },
        {
          id: "soil-health-plus",
          title: "Soil Health Plus",
          price: 6300,
          location: "Uyo, Nigeria",
          seller: "RootCare Agro",
          rating: 4.3,
          image: "/images/products/soil-health-plus.jpg",
          boosted: true,
          subcategory: "soil",
          description: "Enriches soil with organic matter and micronutrients",
          condition: "New",
          postedDate: "2024-05-10",
        },
      ],
      foliar: [
        {
          id: "foliar-boost",
          title: "Foliar Boost",
          price: 3500,
          location: "Benin City, Nigeria",
          seller: "AgroLeaf Express",
          rating: 4.1,
          image: "/images/products/foliar-boost.jpg",
          boosted: false,
          subcategory: "foliar",
          description: "Liquid foliar fertilizer for fast nutrient uptake",
          condition: "New",
          postedDate: "2024-05-11",
        },
        {
          id: "foliar-green",
          title: "Foliar Green",
          price: 3800,
          location: "Awka, Nigeria",
          seller: "FoliarWorks NG",
          rating: 4.4,
          image: "/images/products/foliar-green.jpg",
          boosted: true,
          subcategory: "foliar",
          description: "Enhances leaf chlorophyll and plant vigor",
          condition: "New",
          postedDate: "2024-05-12",
        },
      ],
    },
  },
  animalFeed: {
    name: "Animal Feed",
    description: "Nutritious feed to promote animal growth and health",
    icon: "🍖",
    subcategories: [
      { id: "preventive", name: "Preventive" },
      { id: "curative", name: "Curative" },
      { id: "supplement", name: "Supplement" },
      { id: "powder", name: "Powder" },
      { id: "oral", name: "Oral" },
      { id: "injectable", name: "Injectable" },
    ],
    products: {
      supplement: [
        {
          id: "feed001",
          title: "High Protein Broiler Feed",
          description: "Formulated for rapid growth in broiler chickens.",
          subcategory: "supplement",
          price: 12000,
          unit: "50kg bag",
          image: "/products/feed/high-protein-broiler.jpg",
          location: "Ibadan, Nigeria",
          seller: "AgroVet Credit",
          rating: 4.5,
          boosted: true,
          condition: "Loan",
          postedDate: "2024-05-10",
        }
      ],
      oral: [
        {
          id: "feed002",
          title: "Dairy Cow Pellet Feed",
          description: "Rich in fiber and essential minerals for milk production.",
          subcategory: "oral",
          price: 9500,
          unit: "25kg bag",
          image: "/products/feed/dairy-cow-pellet.jpg",
          location: "Ibadan, Nigeria",
          seller: "AgroVet Credit",
          rating: 4.5,
          boosted: true,
          condition: "Loan",
          postedDate: "2024-05-10",
        }
      ],
      injectable: [
        {
          id: "feed003",
          title: "Layer Mash Feed",
          description: "Boosts egg production and improves shell strength.",
          subcategory: "injectable",
          price: 8700,
          unit: "25kg bag",
          image: "/products/feed/layer-mash.jpg",
          location: "Ibadan, Nigeria",
          seller: "AgroVet Credit",
          rating: 4.5,
          boosted: true,
          condition: "Loan",
          postedDate: "2024-05-10",
        }
      ],
      starter: [
        {
          id: "feed004",
          title: "Chick Starter Feed",
          description: "Specially formulated for healthy chick growth.",
          subcategory: "starter",
          price: 8000,
          unit: "10kg bag",
          image: "/products/feed/chick-starter.jpg",
          location: "Ibadan, Nigeria",
          seller: "AgroVet Credit",
          rating: 4.5,
          boosted: true,
          condition: "Loan",
          postedDate: "2024-05-10",
        }
      ]
    },
  },
  animalPharmacy: {
    name: "Animal Pharmacy",
    description: "Veterinary medications and health supplies",
    icon: "💊",
    subcategories: [
      { id: "preventive", name: "Preventive" },
      { id: "curative", name: "Curative" },
      { id: "supplement", name: "Supplement" },
      { id: "powder", name: "Powder" },
      { id: "oral", name: "Oral" },
      { id: "injectable", name: "Injectable" },
    ],
    products: {
      injectable: [
        {
          id: "med001",
          title: "Vitamin B12 Injection",
          description: "Boosts energy and immunity in livestock.",
          subcategory: "injectable",
          price: 2500,
          unit: "100ml vial",
          image: "/products/pharmacy/vitamin-b12.jpg",
          location: "Ibadan, Nigeria",
          seller: "AgroVet Credit",
          rating: 4.5,
          boosted: true,
          condition: "Loan",
          postedDate: "2024-05-10",
        }
      ],
      oral: [
        {
          id: "med002",
          title: "Anti-Worm Oral Suspension",
          description: "Effective dewormer for poultry and ruminants.",
          subcategory: "oral",
          price: 1800,
          unit: "500ml bottle",
          image: "/products/pharmacy/anti-worm-suspension.jpg",
          location: "Ibadan, Nigeria",
          seller: "AgroVet Credit",
          rating: 4.5,
          boosted: true,
          condition: "Loan",
          postedDate: "2024-05-10",
        }
      ],
    },
  },
  animalAccessories: {
    name: "Animal Accessories",
    description: "Tools and products for managing livestock",
    icon: "🐾",
    subcategories: [
      { id: "drinkers", name: "Drinkers" },
      { id: "cages", name: "Cages" },
      { id: "feeding", name: "Feeding" },
      { id: "transporting", name: "Transporting" },
      { id: "housing", name: "Housing" },
    ],
    products: {
      drinkers: [
        {
          id: "acc001",
          title: "Automatic Chicken Drinker",
          description: "Ensures steady water supply for poultry.",
          subcategory: "drinkers",
          price: 3500,
          unit: "1 unit",
          image: "/products/accessories/auto-drinker.jpg",
          location: "Ibadan, Nigeria",
          seller: "AgroVet Credit",
          rating: 4.5,
          boosted: true,
          condition: "Loan",
          postedDate: "2024-05-10",
        }
      ],
      cages: [
        {
          id: "acc002",
          title: "Plastic Brooder Cage",
          description: "Portable cage ideal for chicks and small animals.",
          subcategory: "cages",
          price: 8000,
          unit: "1 unit",
          image: "/products/accessories/brooder-cage.jpg",
          location: "Ibadan, Nigeria",
          seller: "AgroVet Credit",
          rating: 4.5,
          boosted: true,
          condition: "Loan",
          postedDate: "2024-05-10",
        },
        {
          id: "acc003",
          title: "Metal Brooder Cage",
          description: "Portable cage ideal for dogs and big animals.",
          subcategory: "cages",
          price: 12000,
          unit: "1 unit",
          image: "/products/accessories/brooder-cage.jpg",
          location: "Ibadan, Nigeria",
          seller: "AgroVet Credit",
          rating: 4.5,
          boosted: true,
          condition: "Loan",
          postedDate: "2024-05-10",
        }
      ],
    },
  }

};