import { Category } from "@/types/types";
import {
  TrendingUp,
  MilkIcon as Cow,
  Settings,
  Shield,
  Tractor,
  Heart,
  Sprout,
  Apple,
  Leaf,
  Wheat,
  DollarSign,
  Package,
  Pill,
  Gamepad2,
} from "lucide-react"

export const categories: Category[] = [
  {
    id: "trending",
    name: "Trending",
    icon: TrendingUp,
    subcategories: ["Others"],
    color: "text-orange-500",
    bgColor: "bg-gray-200",
    image: "/icons/0.jpg",
    count: 45,
    href: "/marketplace?filter=trending",
  },
  {
    id: "livestock",
    name: "Livestock & Pets",
    icon: Cow,
    subcategories: ["Poultry", "Cattle", "Goat", "Pig", "Rabbits", "Sheeps", "Turkey"],
    color: "text-green-600",
    bgColor: "bg-gray-200",
    image: "/icons/1.jpg",
    count: 80,
    href: "/category/livestock",
  },
  {
    id: "services",
    name: "Services",
    icon: Settings,
    subcategories: ["Tractor Hiring", "Farm Setup", "Veterinary"],
    color: "text-orange-500",
    bgColor: "bg-gray-200",
    image: "/icons/2.jpg",
    count: 18,
    href: "/category/services",
  },
  {
    id: "insurance",
    name: "Agro Insurance",
    icon: Shield,
    subcategories: ["Crop Insurance", "Livestock Insurance", "Farm Equipment Insurance", "Weather Insurance"],
    color: "text-green-600",
    bgColor: "bg-gray-200",
    image: "/icons/3.jpg",
    count: 5,
    href: "/category/insurance",
  },
  {
    id: "equipment",
    name: "Tractor / Farm Machines",
    icon: Tractor,
    subcategories: ["Tractor", "Sheller", "Sprayer", "Knapsack Sprayer", "Fish Pond", "Others"],
    color: "text-orange-500",
    bgColor: "bg-gray-200",
    image: "/icons/4.jpg",
    count: 45,
    href: "/category/equipments",
  },
  {
    id: "animalMating",
    name: "Animal Mating",
    icon: Heart,
    subcategories: ["Dog", "Goat", "Pig", "AI Service", "Natural Mating"],
    color: "text-green-600",
    bgColor: "bg-gray-200",
    image: "/icons/5.jpg",
    count: 12,
    href: "/category/animalMating",
  },
  {
    id: "agroChemicals",
    name: "Agro Chemicals / Pesticides",
    icon: Sprout,
    subcategories: ["Herbicide", "Pesticide", "Fungicide"],
    color: "text-green-600",
    bgColor: "bg-gray-200",
    image: "/icons/6.jpg",
    count: 28,
    href: "/category/agroChemicals",
  },
  {
    id: "fruits",
    name: "Food / Fruits & Vegetables",
    icon: Apple,
    subcategories: ["Fruit", "Vegetable", "Fresh", "Dried", "Packaged"],
    color: "text-orange-500",
    bgColor: "bg-gray-200",
    image: "/icons/7.jpg",
    count: 320,
    href: "/category/fruits",
  },
  {
    id: "seedlings",
    name: "Seedlings",
    icon: Leaf,
    subcategories: ["Maize", "Soybean", "Groundnut", "Hybrid", "Open-pollination"],
    color: "text-green-600",
    bgColor: "bg-gray-200",
    image: "/icons/8.jpg",
    count: 60,
    href: "/category/seedlings",
  },
  {
    id: "ornamentals",
    name: "Horticulture / Ornamental Crops",
    icon: Wheat,
    subcategories: ["Maize", "Tomatoes", "Cocoa", "Other"],
    color: "text-orange-500",
    bgColor: "bg-gray-200",
    image: "/icons/9.jpg",
    count: 20,
    href: "/category/ornamentals",
  },
  {
    id: "animalLoan",
    name: "Animal Loan",
    icon: DollarSign,
    subcategories: ["Preventive", "Curative", "Supplement"],
    color: "text-green-600",
    bgColor: "bg-gray-200",
    image: "/icons/10.jpg",
    count: 10,
    href: "/category/animalLoan",
  },
  {
    id: "fertilizers",
    name: "Fertilizers",
    icon: Package,
    subcategories: ["NPK", "Urea", "DAP", "Soil", "Foliar"],
    color: "text-green-600",
    bgColor: "bg-gray-200",
    image: "/icons/11.jpg",
    count: 30,
    href: "/category/fertilizers",
  },
  {
    id: "animalFeed",
    name: "Animal Feed",
    icon: Package,
    subcategories: ["Preventive", "Curative", "Supplement", "Powder", "Oral", "Injectable"],
    color: "text-green-600",
    bgColor: "bg-gray-200",
    image: "/icons/12.jpg",
    count: 10,
    href: "/category/animalFeed",
  },
  {
    id: "animalPharmacy",
    name: "Animal Pharmacy",
    icon: Pill,
    subcategories: ["Preventive", "Curative", "Supplement", "Powder", "Oral", "Injectable"],
    color: "text-orange-500",
    bgColor: "bg-gray-200",
    image: "/icons/14.jpg",
    count: 10,
    href: "/category/animalPharmacy",
  },
  {
    id: "animalAccessories",
    name: "Animal Accessories",
    icon: Gamepad2,
    subcategories: ["Drinkers", "Cages", "Feeding", "Transporting", "Housing"],
    color: "text-gray-700",
    bgColor: "bg-gray-200",
    image: "/icons/15.jpg",
    count: 15,
    href: "/category/animalAccessories",
  },
];