export const Cats = [
    "Abyssinian",
    "American Bobtail",
    "American Curl",
    "American Wirehair",
    "Balinese and Javanese",
    "Bengal",
    "Birman",
    "Bombay",
    "British Shorthair",
    "Burmese",
    "Burmilla",
    "Chartreux",
    "Chausie",
    "Colorpoint Shorthair",
    "Cornish Rex",
    "Cymric (Longhaired Manx)",
    "Devon Rex",
    "Donskoy",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Havana Brown",
    "Highlander",
    "Himalayan",
    "Japanese Bobtail",
    "Khao Manee",
    "Kinkalow",
    "Korat",
    "Kurilian Bobtail",
    "Lambkin Dwarf",
    "Laperm",
    "Lykoi",
    "Maine Coon",
    "Manx",
    "Minskin",
    "Munchkin",
    "Nebelung",
    "Norwegian Forest",
    "Ocicat",
    "Ojos Azules",
    "Oriental",
    "Persian",
    "Peterbald",
    "Pixie Bob",
    "Ragdoll",
    "Ragamuffin",
    "Russian Blue",
    "Savannah",
    "Scottish Fold",
    "Selkirk Rex",
    "Serengeti",
    "Siamese",
    "Siberian",
    "Singapura",
    "Snowshoe",
    "Sokoke",
    "Somali",
    "Sphynx",
    "Toyger",
    "Turkish Van",
    "Other",
]