export const Cattles = [
    "Rath Cattle",
"Vestland Fjord Cattle",
"Africander Cattle",
"Akaushi",
"Alberes Cattle",
"Alentejana Cattle",
"Allmogekor Cattle",
"American Braford Cattle",
"American White Park Cattle",
"Amerifax Cattle",
"Amrit Mahal Cattle",
"Anatolian Black Cattle",
"Andalusian Black Cattle",
"Andalusian Grey Cattle",
"Angeln Cattle",
"Angus Cattle",
"Angus Cattle",
"Angus Cattle Registries",
"Ankole Cattle",
"Ankole Cattle",
"Ankole-Watusi Cattle",
"Argentine Criollo Cattle",
"Asturian Mountain Cattle",
"Asturian Valley Cattle",
"Aubrac Cattle",
"Aulie-Ata Cattle",
"Australian Braford Cattle",
"Australian Friesian Sahiwal Cattle",
"Australian Lowline Cattle",
"Australian Milking Zebu Cattle",
"Ayrshire Cattle",
"Ayrshire Cattle",
"Ayrshire Cattle Registries",
"Azaouak - NW Niger",
"Bachaur Cattle",
"Baladi Cattle",
"Baltata Romaneasca Cattle",
"Barka Cattle",
"Barka Cattle",
"Barzona Cattle",
"Barzona Cattle Registries",
"Bazadais Cattle",
"Béarnais Cattle",
"Beefalo Cattle",
"Beefalo Cattle Registries",
"Beefmaker Cattle",
"Beefmaster Cattle",
"Beefmaster Cattle Registries",
"Belarus Red Cattle",
"Belgian Blue Cattle",
"Belgian Blue Cattle Registries",
"Belgian Red Cattle",
"Belmont Adaptaur Cattle",
"Belmont Red Cattle",
"Belted Galloway Cattle",
"Belted Galloway Cattle Registries",
"Bengali Cattle",
"Berrendas Cattle",
"Bhagnari Cattle",
"Blacksided Trondheim and Norland Cattle",
"Blanca Cacereña/White Cáceres Cattle",
"Blanco Orejinegro Cattle",
"Blonde d'Aquitaine Cattle",
"Blonde d'Aquitaine Cattle Registries",
"Boran Cattle",
"Boran Cattle",
"Bordelais Cattle",
"Brahman Cattle",
"Brahman Cattle Registries",
"Brahmousin Cattle",
"Brangus Cattle",
"Brangus Cattle Registries",
"Braunvieh Cattle",
"British White Cattle",
"Brown Swiss Cattle",
"Busa Cattle",
"Cachena Cattle",
"Canadian Highland Cattle",
"Canadienne Cattle",
"Canary Island Cattle",
"Canchim Cattle",
"Carinthian Blond Cattle",
"Cattle",
"Caucasian Cattle",
"Channi Cattle",
"Charbray Cattle",
"Charbray Cattle Registries",
"Charolais Cattle",
"Charolais Cattle Registries",
"Chianina Cattle",
"Chianina Cattle Registries",
"Chinampo Cattle",
"Chinese Black-and-White Cattle",
"Cholistani Cattle",
"Corriente Cattle",
"Costeño con Cuernos Cattle",
"Dajal Cattle",
"Damascus Cattle",
"Damascus Cattle",
"Damietta Cattle",
"Damietta Cattle",
"Dangi Cattle",
"Danish Jersey Cattle",
"Danish Red Cattle",
"Deoni Cattle",
"Devon Cattle",
"Devon Cattle Registries",
"Dexter Cattle",
"Dexter Cattle",
"Dhanni Cattle",
"Dølafe Cattle",
"Droughtmaster Cattle",
"Dulong Cattle",
"Dutch Belted (Lakenvelder) Cattle",
"Dutch Belted (Lakenvelder) Cattle",
"Dutch Friesian Cattle",
"East Anatolian Red Cattle",
"Enderby Island Cattle",
"English Longhorn Cattle",
"Estonian Red Cattle",
"Evolène",
"Fighting Cattle",
"Finnish Cattle",
"Fjall Cattle",
"Florida Cracker Cattle",
"Florida Cracker/Pineywoods Cattle Registries",
"Galician Blond Cattle",
"Galloway cattle",
"Galloway Cattle Registries",
"Galloway Cattle Registries",
"Gaolao Cattle",
"Gascon Cattle",
"Gelbvieh Cattle",
"Gelbvieh Cattle Registries",
"German Angus Moiled Cattle",
"German Red Pied Cattle",
"Gir Cattle",
"Gir Cattle",
"Glan Cattle",
"Gloucester Cattle",
"Gobra",
"Greek Shorthorn Cattle",
"Greek Steppe Cattle",
"Groningen Cattle",
"Guernsey Cattle",
"Guernsey Cattle",
"Guzerat Cattle",
"Hallikar Cattle",
"Hariana Cattle",
"Harton Cattle",
"Hays Converter Cattle",
"Hereford Cattle",
"Hereford Cattle",
"Hereford Cattle Registries",
"Herens Cattle",
"Herens Cattle Registries",
"Highland Cattle",
"Highland Cattle",
"Hinterwald Cattle",
"Hinterwald Cattle Registries",
"Holando-Argentino Cattle",
"Holstein Cattle",
"Holstein Cattle",
"Horro Cattle",
"Horro Cattle",
"Hungarian Grey Cattle",
"Icelandic Cattle",
"Illawarra Cattle",
"Indo-Brazilian Cattle",
"Irish Moiled Cattle",
"Israeli Holstein Cattle",
"Israeli Red Cattle",
"Istoben Cattle",
"Jamaica Black Cattle",
"Jamaica Hope Cattle",
"Jamaica Red Cattle",
"Jaulan Cattle",
"Jaulan Cattle",
"Jersey Cattle",
"Jersey Cattle",
"Kangayam Cattle",
"Kankrej Cattle",
"Karan Fries Cattle",
"Karan Swiss Cattle",
"Kazakh Cattle",
"Kenwariya Cattle",
"Kerry Cattle",
"Kerry Cattle",
"Kherigarh Cattle",
"Khillari Cattle",
"Kholmogory Cattle",
"Kilis Cattle",
"Krishna Valley Cattle",
"Kurdi Black Cattle",
"Kuri Cattle",
"Latvian Brown (Buraya latviiskaya) Cattle",
"Limousin Cattle",
"Limousin Cattle",
"Limousin Cattle Registries",
"Limpurger Cattle",
"Lincoln Red Cattle",
"Lithuanian Red Cattle",
"Lohani Cattle",
"Lourdais Cattle",
"Luing Cattle",
"Luing Cattle",
"Madagascar Zebu Cattle",
"Maine-Anjou Cattle",
"Malvi Cattle",
"Mandalong Cattle",
"Marchigiana Cattle",
"Marchigiana Cattle Registries",
"Maremmana Cattle",
"Masai Cattle",
"Mashona Cattle",
"Mashona Cattle",
"Maure Cattle",
"Mazandarani Cattle",
"Meuse-Rhine-Yssel Cattle",
"Mewati Cattle",
"Milking Devon Cattle",
"Milking Shorthorn Cattle",
"Modicana Cattle",
"Montbéliard Cattle",
"Morucha Cattle",
"Murboden Cattle",
"Murray Grey Cattle",
"Murray Grey Cattle Registries",
"Muturu - West African Dwarf Shorthorn",
"N'dama Cattle",
"N'dama Cattle",
"Nagori Cattle",
"Nanyang Cattle",
"Nelore Cattle",
"Nelore Cattle",
"Nimari Cattle",
"Normande Cattle",
"Norwegian Red Cattle",
"Norwegian Red Cattle Registries",
"Ongole Cattle",
"Oropa Cattle",
"Ovambo Cattle",
"Parthenais Cattle",
"Parthenais Cattle Registries",
"Philippine Native Cattle",
"Piedmontese Cattle",
"Piedmontese Cattle Registries",
"Pinzgauer Cattle",
"Polish Red Cattle",
"Polled Hereford",
"Ponwar Cattle",
"Qinchuan Cattle",
"Rathi Cattle",
"Rätien Gray",
"Red Angus Cattle",
"Red Angus Cattle",
"Red Brangus Cattle",
"Red Brangus Cattle Registries",
"Red Fulani or Mbororo",
"Red Pied Friesian Cattle",
"Red Poll Cattle",
"Red Poll Cattle",
"Red Poll Cattle Registries",
"Red Polled Østland Cattle",
"Red Sindhi Cattle",
"Red Steppe Cattle",
"Reggiana Cattle",
"Retinta Cattle",
"Rojhan Cattle",
"Romagnola Cattle Registries",
"Romosinuano Cattle",
"Russian Black Pied Cattle",
"RX3 Cattle",
"Sahiwal Cattle",
"Salers Cattle",
"Salers Cattle",
"Salers Cattle Registries",
"Salorn Cattle",
"San Martinero Cattle",
"Sanhe Cattle",
"Santa Cruz Cattle",
"Santa Gertrudis Cattle",
"Santa Gertrudis Cattle",
"Sarabi Cattle",
"Senepol Cattle",
"Shetland Cattle",
"Shorthorn Cattle",
"Shorthorn Cattle",
"Shorthorn Cattle Registries",
"Siboney Cattle",
"Simbrah Cattle",
"Simbrah Cattle",
"Simmental Cattle",
"Siri Cattle",
"Slovenian Cika Cattle",
"South Devon Cattle",
"South Devon Cattle Registries",
"Sudanese Fulani",
"Sussex Cattle",
"Sussex Cattle",
"Sussex Cattle Registries",
"Swedish Friesian Cattle",
"Swedish Red Polled Cattle",
"Swedish Red-and-White Cattle",
"Tarentaise Cattle",
"Telemark Cattle",
"Texas Longhorn Cattle",
"Texon Cattle",
"Tharparkar Cattle",
"Tswana Cattle",
"Tswana Cattle",
"Turkish Grey Steppe Cattle",
"Ukrainian Beef Cattle",
"Ukrainian Grey Cattle",
"Ukrainian Whitehead Cattle",
"Umblachery Cattle",
"Ural Black Pied Cattle",
"Vestland Red Polled Cattle",
"Vosges Cattle",
"Wagyu Cattle Registries",
"Waygu Cattle",
"Waygu Cattle",
"Welsh Black Cattle",
"White Park Cattle",
"White Park Cattle",
"Yanbian Cattle",
"Chinese Mongolian cattle",
"Chinese Xinjiang Brown cattle",
"Gelbray Cattle",
"American Breed cattle",
"Other",
]