export const Dogs = [
    "Affenpinscher",
"Afghan Hound",
"Ainu",
"Airedale Terrier",
"Akita",
"Alaskan Husky",
"Alaskan Klee Kai",
"Alaskan Malamute",
"American Bulldog",
"American Eskimo Dog",
"American Foxhound",
"American Pit Bull Terrier",
"American Staffordshire Terrier",
"American Water Spaniel",
"Anatolian Shepherd Dog",
"Australian Cattle Dog",
"Australian Shepherd",
"Australian Terrier",
"Basenji",
"Basset Hound",
"Beagle",
"Bearded Collie",
"Beauceron",
"Bedlington terrier",
"Belgian Malinois",
"Belgian sheepdog",
"Belgian Tervuren",
"Bergamasco",
"Bernese Mountain Dog",
"Bichon Frise",
"Black and Tan Coonhound",
"Black Russian Terrier",
"Bloodhound",
"Bolognese",
"Border Collie",
"Border Terrier",
"Borzoi",
"Boston Terrier",
"Bouvier des Flandres",
"Boxer",
"Biard",
"Brittany",
"Brussels Griffon",
"Bull Terrier",
"Bulldog",
"Bullmastiff",
"Cairn Terrier",
"Canaan Dog",
"Cane Corso",
"Cardigan Welsh Corgi",
"Catahoula Leopard Dog",
"Cavalier King Charles Spaniel",
"Caucasian",
"Cesky Terrier",
"Chesapeake Bey Retriever",
"Chihuahua",
"Chinese Crested",
"Chinese Shar-Pei",
"Chinook",
"Chow Chow",
"Clumber Spaniel",
"Cocker Spaniel",
"Collie",
"Coton de tular",
"Curly-coated Retriever",
"Dauchshund",
"Dalmation",
"Dandie Dinmount Terrier",
"Dingo",
"Doberman Pinscher",
"English Cocker Spaniel",
"English Foxhoud",
"English Setter",
"English Springer Spaniel",
"English Toy Spaniel",
"Estrela Mountain Dog",
"Field Spaniel",
"Finnish Spitz",
"Flat-coated Retriever",
"French Bulldog",
"German Pinscher",
"German Shepard dog",
"German short-haired Pointer",
"German wire-haired Pointer",
"Giant Schnauzer",
"Glen of Imaal Terrier",
"Golden Retriever",
"Gordon Setter",
"Great Dane",
"Great Pyreness",
"Greater Swiss mountain dog",
"Greyhound",
"Harrier",
"Havanese",
"Ibizan Hound",
"Icelandic Sheepdog",
"Irish Red and White Setter",
"Irish Setter",
"Irish Terrier",
"Irish Water Spaniel",
"Irish Wolfhound",
"Italian Greyhound",
"Jack Russell Terrier",
"Japanese Chin",
"Japanese Terrier",
"Keeshond",
"Kerry Beagle",
"Kerry Blue Terrier",
"Komondor",
"Kuvasz",
"Labradoodle",
"Labrador Retreiver",
"Lakeland Terrier",
"Lancashire Heeler",
"Leonberber",
"Lhasa Apso",
"Lowchen",
"Maltese",
"Manchester Terrier",
"Mastiff",
"Miniature Bull Terrier",
"Miniature Pinscher",
"Miniature Schnauzer",
"Neapolitan Mastiff",
"Newfoundland",
"Norfolk Terrier",
"Nowegian Elkhound",
"Norewegian Lundehund",
"Norwich Terrier",
"Nova Scotia Duck Tolling Retriever",
"Old English Sheepdog",
"Otterhound",
"Papillon",
"Parson Russell Terrier",
"Pekingese",
"Pembroke Welsh Corgi",
"Petit Basset Griffon Vendeen",
"Pharaoh Hound",
"Plott",
"Pointer",
"Ploish Lowland Sheepdog",
"Pomeranian",
"Poodle",
"Portuguese Water Dog",
"Pug",
"Puli",
"Rat Terrier",
"Redbone Coonhound",
"Rhodesian Ridgeback",
"Rottweiler",
"Saint Bernard",
"Saluki",
"Samoyed",
"Schipperke",
"Scottish Deerhound",
"Sealyham Terrier",
"Shetland Sheepdog",
"Shiba Inu",
"Shih Tzu",
"Siberian Husky",
"Silky Terrier",
"Skye Terrier",
"Sloughi",
"Smooth Fox Terrier",
"Soft Coated Wheaten Terrier",
"Spanish Mastiff",
"Spinone Italiano",
"Staffordshire Bull Terrier",
"Standard Shnauzer",
"Sussex Spaniel",
"Swedish Vallhund",
"Thai Ridgeback",
"Tibetan Mastiff",
"Tibetan Terrier",
"Toy Fox Terrier",
"Toy Manchester",
"Toy Poodle",
"Transylvanian Hound",
"Vizsla",
"Volpino Italiano",
"Weimaraner",
"Welsh Springer Spaniel",
"Welsh Terrier",
"West Highland White Terrier",
"Whippet",
"Wire Fox Terrier",
"Wirehaired Pointing Griffon",
"Xoloitzcuintli",
"Yorkshire Terrier",
"Other",
]