export const Pigs = [
    "Angeln Saddleback	",
"American Yorkshire",
"Arapawa",
"Berkshire",
"British Saddleback",
"Chato Murciano",
"Choctaw",
"Danish Protest",
"Duroc",
"Dutch Landrace",
"Essex",
"Fengjing",
"Gloucestershire Old Spots",
"Hampshire",
"Hereford",
"Italian Landrace",
"Kunekune",
"Lacombe",
"Large Black",
"Large White",
"Mangalica",
"Meishan",
"Middle White",
"Mora Romagnola",
"Mulefoot",
"Nero Siciliano",
"Ossabaw Island",
"Oxford Sandy and Black",
"Red Wattle",
"Swedish Landrace",
"Swabian-Hall",
"Tamworth",
"Turopolje",
"Pot-bellied",
"Welsh",
"Wessex Saddleback",
"Other",
]