export const Sheep = [
    "Acipayam",
"Adal",
"Afghan Arabi",
"Africana",
"Alai",
"Alcarrena",
"Algarvechurro",
"Algerian Arab",
"Altai",
"Altay",
"American Blackbelly",
"Apennine",
"Arabi",
"Arapawa Island",
"Awassi",
"Balkhi",
"Baluchi",
"Balwen Welsh Mountain",
"Barbados Blackbelly",
"Bavarian Forest",
"Bentheimer Landschaf",
"Bergamasca",
"Beulah Speckled-Face",
"Bibrik",
"Biellese",
"Blackhead Persian",
"Black Welsh Mountain Sheep",
"Bleu du Maine",
"Bluefaced Leicester",
"Bond",
"Booroola Merino",
"Border Leicester",
"Boreray",
"Bovska",
"Braunes Bergschaf",
"Brazilian Somali",
"Brecknock Hill Cheviot",
"British Milk Sheep",
"Brillenschaf",
"Bündner Oberland",
"California Red",
"California Variegated Mutant",
"Campanian Barbary",
"Castlemilk Moorit",
"Charollais",
"Cheviot",
"Chios",
"Cholistani",
"Clun Forest",
"Coburger Fuchsschaf",
"Columbia",
"Comeback",
"Comisana",
"Coopworth",
"Cormo",
"Corriedale",
"Cotswold",
"Criollo",
"Dala",
"Damani",
"Damara",
"Danish Landrace",
"Dartmoor",
"Debouillet",
"Delaine Merino",
"Dorper",
"Derbyshire Gritstone",
"Devon Closewool",
"Deutsches Blaukoepfiges Fleischschaf",
"Dorset",
"Dorset Down",
"Drysdale",
"Elliottdale",
"Exmoor Horn",
"Fabrianese",
"Faeroes",
"Finnsheep",
"Fonthill Merino",
"Friesian Milk Sheep",
"Galway",
"Gansu Alpine Fine-wool",
"Gentile di Puglia",
"German Blackheaded Mutton",
"German Mountain",
"German Mutton Merino",
"German Whiteheaded Mutton",
"Gotland Sheep",
"Graue Gehoernte Heidschnucke",
"Gromark",
"Gulf Coast Native",
"Gute",
"Hampshire",
"Han",
"Harnai",
"Hasht Nagri",
"Hazaragie",
"Hebridean",
"Herdwick",
"Hill Radnor",
"Hog Island Sheep",
"Hu",
"Icelandic",
"Ile-de-France",
"Istrian Pramenka",
"Jacob",
"Jezersko-Solcava",
"Kachhi",
"Kajli",
"Karakul",
"Katahdin",
"Kerry Hill",
"Kooka",
"Langhe",
"Lati",
"Leicester Longwool",
"Leineschaf",
"Lincoln",
"Llanwenog",
"Lleyn",
"Lohi",
"Lonk",
"Luzein",
"Manx Loaghtan",
"Masai",
"Massese",
"Medium-Wool Merino",
"Mehraban",
"Merinolandschaf",
"Moghani",
"Montadale",
"Morada Nova",
"mouflon",
"Navajo-Churro",
"Norfolk Horn",
"North Country Cheviot",
"Norwegian Fur",
"Old Norwegian",
"Orkney",
"Ossimi",
"Oxford",
"Pagliarola",
"Pelibüey",
"Perendale",
"Pinzirita",
"Pitt Island",
"Poll Merino",
"Polwarth",
"Polypay",
"Pomeranian Coarsewool",
"Portland",
"Priangan",
"Rabo Largo",
"Racka",
"Rambouillet",
"Rasa Aragonesa",
"Red Engadine",
"Rhoenschaf",
"Rideau Arcott",
"Romanov",
"Romney",
"Rouge de l'Quest",
"Rough Fell",
"Royal White",
"Rya",
"Ryeland",
"Rygja",
"Sahel-type",
"Santa Cruz",
"Santa Inês",
"Sardinian",
"Sar Planina",
"Scottish Blackface",
"Sicilian Barbary",
"Shetland",
"Shropshire",
"Skudde",
"Soay",
"Somali",
"Sopravissana",
"South African Merino",
"South African Mutton Merino",
"South Suffolk",
"Southdown",
"South Wales Mountain",
"Spælsau",
"Spiegel",
"St. Croix (Virgin Island White)",
"Steigar",
"Steinschaf",
"Strong Wool Merino",
"Suffolk",
"Sumavska",
"Swaledale",
"Swedish Fur Sheep",
"Targhee",
"Teeswater",
"Texel",
"Thalli",
"Tong",
"Touabire",
"Tsurcana",
"Tunis",
"Tyrol Mountain",
"Uda",
"Ujumqin",
"Ushant",
"Valais Blacknose",
"Vendéen",
"Walachenschaf",
"Wallis Country Sheep",
"Waziri",
"Weisse Hornlose Heidschnucke",
"Welsh Hill Speckled Face",
"Welsh Mountain",
"Welsh Mountain Badger Faced",
"Wensleydale",
"West African Dwarf",
"White Suffolk",
"Whiteface Dartmoor",
"Whiteface Woodland",
"Wiltshire Horn",
"Xinjiang Finewoo",
"Other",
]